# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.continuous-integration\\appveyor\\windows_sdk.cmd"

  matrix:

      - PYTHON_VERSION: "3.6"
        platform: x64
        PYTHON_ARCH: "64"
      - PYTHON_VERSION: "2.7"
        platform: x86
        PYTHON_ARCH: "32"

cache:
    - '%LOCALAPPDATA%\pip\Cache'

install:
    # Clear tmpdir (sometimes left behind by appveyor?)
    - rmdir /s /q %APPVEYOR_BUILD_FOLDER%\\tmp & exit /b 0

    # Install miniconda using a powershell script.
    - "powershell .continuous-integration/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Install the build and runtime dependencies of the project.
    - "conda update -q --yes conda"

    # Tell conda to not use hardlinks: on Windows it's not possible
    # to delete hard links to files in use, which causes problem when
    # trying to cleanup environments during the tests
    - "conda config --set always_copy True"
    - "conda config --set allow_softlinks False"

    # Create a conda environment
    - "conda create -q --yes -n test python=%PYTHON_VERSION%"
    - "activate test"

    # Check that we have the expected version of Python
    - "python --version"

    # Install specified version of dependencies
    - "conda install -q --yes six pip pytest pytest-xdist numpy"

    # In-place build
    - "%CMD_IN_ENV% python setup.py build_ext -i"

# Not a .NET project
build: false

test_script:
    - "python -m pytest -l --basetemp=%APPVEYOR_BUILD_FOLDER%\\tmp -vv -n 5 --dist=loadscope test"

after_build:
    # Clear up pip cache
    - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -mtime +360 -delete
    - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -size +10M -delete
    - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -empty -delete
    # Show size of cache
    - C:\cygwin\bin\du -hs "%LOCALAPPDATA%\pip\Cache"
