# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.continuous-integration\\appveyor\\windows_sdk.cmd"

  matrix:

      - PYTHON_VERSION: "2.7"
        platform: x64
        PYTHON_ARCH: "64"
      - PYTHON_VERSION: "2.7"
        platform: x86
        PYTHON_ARCH: "32"
      - PYTHON_VERSION: "3.4"
        platform: x64
        PYTHON_ARCH: "64"

install:
    # Install miniconda using a powershell script.
    - "powershell .continuous-integration/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Install the build and runtime dependencies of the project.
    - "conda update --yes conda"
    # Create a conda environment
    - "conda create -q --yes -n test python=%PYTHON_VERSION%"
    - "activate test"

    # Check that we have the expected version of Python
    - "python --version"

    # Install specified version of dependencies
    - "conda install -q --yes six pytest numpy"

# Not a .NET project
build: false

test_script:
  - "%CMD_IN_ENV% python setup.py test -a --tb=native"
